### ISSUE TITLE
Fala Dev! Beleza?

### ISSUE THREAD

**Issue by lucaspdroz** [gustavoalmei/PlayerMusic#1]
Estava vendo o seu projeto, e achei muito massa!

Vou deixar aqui algumas ideias para você melhorar no futuro:

1- Ajustar a url do Github-corner
Atualmente não leva ao seu código: `href="https://your-url"`

Outra coisa que seria interessante, transformar suas variáveis em um objeto, com objetivo de melhorar a leitura de código 

```let audioPlayer = document.querySelector('#audioPlayer')
let progress = document.querySelector('#progress')
let audioPlay = document.querySelector('#playPause')
let advTime = document.querySelector('#advTime')
let backTime = document.querySelector('#backTime')
let MinutesSeconds = document.querySelector('#MinutesSeconds')
let MinutesSecondsLive = document.querySelector('#MinutesSecondsLive')
let InputVolume = document.querySelector('#InputVolume')
let sound = document.querySelector('#sound')
let NextMusic = document.querySelector('#NextMusic')
let backMusic = document.querySelector('#backMusic')
let songs = document.querySelector('#songs')
let author = document.querySelector('#author')
let nameMusic = document.querySelector('#nameMusic')
let photoAlbum = document.querySelector('#photoAlbum')
```

Voce pode alterar para algo assim:
```
const player = {
  audioPlayer: document.querySelector('#audioPlayer'),
  progress : document.querySelector('#progress'),
  audioPlay : document.querySelector('#playPause'),
  advTime : document.querySelector('#advTime'),
  backTime : document.querySelector('#backTime'),
...
}
```

E acessar assim:
`player.audioPlayer`

Ou se quiser avançar mais um pouco, você pode fazer a destructuring do objeto player:

`const {audioPlayer,progress ,audioPlay, ... }  = player`

E acessar as propriedades assim:

audioPlayer

Achei muito massa o seu projeto, Continua estudando, vc vai longe, CHEERS o/

**Comment by gustavoalmei** [comment]
Woooow que de mais cara, sério, curti de mais as dicas, pode deixar que vou aplicar elas, o GitHub Corner eu fui vê no outro dia que fui dar uma olhada no códico, e acabei esquecendo de ajusta. Valeuzão pela ajuda. 😄
